import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';

import 'generated_source_check.dart';

/// Generates semantic factories and typed locale dispatch from the stable Copy
/// API. `--check` detects stale output without rewriting user source.
void main(List<String> args) {
  final CompilationUnit unit = parseString(
    content: File('lib/core/copy/copy.dart').readAsStringSync(),
  ).unit;
  final ClassDeclaration cls = unit.declarations
      .whereType<ClassDeclaration>()
      .single;
  const String generated =
      '// GENERATED CODE - DO NOT MODIFY BY HAND\n// Generated by tool/generate_copy_messages.dart.\n\n';
  final StringBuffer factory = StringBuffer(
    '$generated'
    "import 'package:tapture/app/theme/markup_ink.dart';\n\nimport 'copy.dart';\n\n"
    '/// Semantic messages for context-free state, failures and persistence.\nfinal class CopyMessages {\n  /// Creates the shared stateless factory.\n  const CopyMessages();\n',
  );
  final StringBuffer resolver = StringBuffer(
    '$generated'
    "import 'package:tapture/app/theme/markup_ink.dart';\nimport 'package:tapture/core/errors/failure.dart';\n\nimport 'localized_copy.dart';\nimport 'localized_message.dart';\n\n"
    '/// Resolves typed headless messages in this widget\'s current catalogue.\nextension LocalizedCopyResolver on LocalizedCopy {\n  /// Renders a semantic member; invalid arguments retain the audit fallback.\n  String resolve(LocalizedMessage message) {\n    try { return _resolve(message); } on FormatException { return message.fallback; } on TypeError { return message.fallback; } on ArgumentError { return message.fallback; }\n  }\n\n  String _resolve(LocalizedMessage message) => switch(message.key) {\n',
  );
  for (final MethodDeclaration member
      in (cls.body as BlockClassBody).members.whereType<MethodDeclaration>()) {
    if (member.returnType?.toSource() != 'String' ||
        !member.isStatic ||
        member.name.lexeme.startsWith('_')) {
      continue;
    }
    final String name = member.name.lexeme;
    final String doc = member.documentationComment == null
        ? '/// Catalogue message $name.'
        : member.documentationComment!.tokens
              .map((token) => token.lexeme)
              .join('\n');
    if (member.isGetter) {
      factory.writeln(
        '$doc\n  LocalizedMessage get $name => LocalizedMessage(key:\'$name\',fallback:Copy.$name);',
      );
      resolver.writeln("    '$name' => $name,");
      continue;
    }
    final List<String> call = <String>[],
        typed = <String>[],
        arguments = <String>[];
    for (final FormalParameter parameter in member.parameters!.parameters) {
      final FormalParameter base = parameter is DefaultFormalParameter
          ? parameter.parameter
          : parameter;
      if (base is! SimpleFormalParameter ||
          base.name == null ||
          base.type == null) {
        throw StateError('Unsupported parameter $name/$base');
      }
      final String parameterName = base.name!.lexeme,
          type = base.type!.toSource();
      call.add('${parameter.isNamed ? '$parameterName: ' : ''}$parameterName');
      typed.add(
        '${parameter.isNamed ? '$parameterName: ' : ''}${_read(type, parameterName)}',
      );
      arguments.add(
        "'$parameterName': LocalizedMessage.encodeArgument($parameterName)",
      );
    }
    factory.writeln(
      '$doc\n  LocalizedMessage $name${member.parameters!.toSource()} => LocalizedMessage(key:\'$name\',fallback:Copy.$name(${call.join(',')}),arguments:<String,Object?>{${arguments.join(',')}});',
    );
    resolver.writeln("    '$name' => $name(${typed.join(',')}),");
  }
  factory.writeln('}');
  resolver.writeln('''    _ => message.fallback,
  };

  /// Localizes a typed failure while its .message stays English for audit.
  String failureMessage(Failure failure) => failure.localizedMessage == null
      ? failure.message : resolve(failure.localizedMessage!);

  /// Localizes the recovery without changing the failure's stored value.
  String? failureRecovery(Failure failure) => failure.localizedRecovery == null
      ? failure.recoveryAction : resolve(failure.localizedRecovery!);

  /// Renders optional state metadata without interpreting the fallback text.
  String? stateText(LocalizedMessage? semantic, String? fallback) =>
      semantic == null ? fallback : resolve(semantic);
}
''');
  _write(
    'lib/core/copy/copy_messages.g.dart',
    factory.toString(),
    check: args.contains('--check'),
  );
  _write(
    'lib/core/copy/localized_copy_resolver.g.dart',
    resolver.toString(),
    check: args.contains('--check'),
  );
}

String _read(String type, String name) {
  final bool nullable = type.endsWith('?');
  final String base = nullable ? type.substring(0, type.length - 1) : type;
  final String raw = "message.argument('$name')";
  final String read;
  if (base == 'String') {
    read =
        '($raw is LocalizedMessage ? resolve($raw as LocalizedMessage) : $raw as String)';
  } else if (base == 'MarkupInk') {
    read = 'MarkupInk.values.byName($raw as String)';
  } else if (base.startsWith('List<')) {
    read =
        '($raw as List<Object?>).cast<${base.substring(5, base.length - 1)}>()';
  } else if (base.startsWith('Map<')) {
    read =
        '($raw as Map<Object?,Object?>).cast<${base.substring(4, base.length - 1)}>()';
  } else {
    read = '$raw as $base';
  }
  return nullable ? "$raw == null ? null : $read" : read;
}

void _write(String path, String content, {required bool check}) {
  final File file = File(path);
  if (check) {
    final String? problem = generatedSourceProblem(
      path: path,
      actual: file.existsSync() ? file.readAsStringSync() : null,
      expected: content,
      generator: 'tool/generate_copy_messages.dart',
    );
    if (problem != null) {
      stderr.writeln(problem);
      exitCode = 1;
    }
  } else {
    file.writeAsStringSync(content);
  }
}
