import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';

import 'generated_source_check.dart';

/// Generates only domain-used English members and their semantic factories.
/// The output imports no Flutter catalogue, widget or presentation enum.
void main(List<String> args) {
  final Set<String> members = <String>{};
  final List<String> pureImports = <String>[];
  for (final File file in Directory(
    'lib',
  ).listSync(recursive: true).whereType<File>()) {
    final String path = file.path.replaceAll('\\', '/');
    if (!path.endsWith('.dart') || path.endsWith('.g.dart')) continue;
    final String source = file.readAsStringSync();
    if (!path.contains('/domain/') &&
        !source.contains(
          "import 'package:tapture/core/copy/domain_copy.g.dart';",
        )) {
      continue;
    }
    if (path.contains('/domain/') &&
        RegExp(r'\bDomainCopy\s*\.').hasMatch(source)) {
      pureImports.add(path.substring(4));
    }
    for (final RegExpMatch match in RegExp(
      r'\b(?:DomainCopy|Copy)\s*\.\s*(?:messages\s*\.\s*)?(\w+)',
    ).allMatches(source)) {
      if (match[1] != 'messages') members.add(match[1]!);
    }
  }
  final ClassDeclaration facade = _class('lib/core/copy/copy.dart');
  final ClassDeclaration localized = _class(
    'lib/core/copy/localized_copy.dart',
  );
  final ClassDeclaration english = _class(
    'lib/core/copy/l10n/app_localizations_en.g.dart',
    name: 'AppLocalizationsEn',
  );
  final Map<String, MethodDeclaration> localMethods =
      <String, MethodDeclaration>{
        for (final MethodDeclaration m
            in (localized.body as BlockClassBody).members
                .whereType<MethodDeclaration>())
          m.name.lexeme: m,
      };
  final Map<String, MethodDeclaration> englishMethods =
      <String, MethodDeclaration>{
        for (final MethodDeclaration m
            in (english.body as BlockClassBody).members
                .whereType<MethodDeclaration>())
          m.name.lexeme: m,
      };
  final Set<String> selected = <String>{...members};
  final Set<String> catalogue = <String>{};
  var previous = -1;
  while (previous != selected.length) {
    previous = selected.length;
    for (final String name in selected.toList()) {
      final MethodDeclaration? method = localMethods[name];
      if (method == null) throw StateError('Domain member missing: $name');
      if (method.toSource().contains('MarkupInk')) {
        throw StateError('Domain member depends on UI: $name');
      }
      for (final RegExpMatch m in RegExp(
        r'_catalog\.(\w+)',
      ).allMatches(method.toSource())) {
        if (m[1] != 'localeName') catalogue.add(m[1]!);
      }
      for (final String candidate in localMethods.keys) {
        if (RegExp('\\b$candidate\\s*\\(').hasMatch(method.body.toSource()) &&
            candidate != name) {
          selected.add(candidate);
        }
      }
      if (method.body.toSource().contains('_withLocale')) {
        selected.add('_formatLocale');
      }
    }
  }
  final StringBuffer out = StringBuffer(
    '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_domain_copy.dart.
// ignore_for_file: type=lint

// ignore: unused_import
import 'package:intl/intl.dart';
// ignore: unused_import
import 'package:intl/intl.dart' as intl;

import 'localized_message.dart';
export 'localized_message.dart';

/// English audit copy and semantic messages for pure Dart domain boundaries.
abstract final class DomainCopy {
  static const _DomainFormatter _english = _DomainFormatter();
  /// Serializable semantic factories without a Flutter dependency.
  static const _DomainMessages messages = _DomainMessages();
''',
  );
  final StringBuffer factories = StringBuffer(
    'class _DomainMessages {\n  const _DomainMessages();\n',
  );
  for (final MethodDeclaration method
      in (facade.body as BlockClassBody).members
          .whereType<MethodDeclaration>()) {
    final String name = method.name.lexeme;
    if (!members.contains(name)) continue;
    if (method.returnType?.toSource() != 'String') {
      throw StateError('Unsupported domain copy type: $name');
    }
    out.writeln(method.toSource());
    if (method.isGetter) {
      factories.writeln(
        "LocalizedMessage get $name => LocalizedMessage(key:'$name',fallback:DomainCopy.$name);",
      );
      continue;
    }
    final List<String> call = <String>[], parameters = <String>[];
    for (final FormalParameter parameter in method.parameters!.parameters) {
      final String p = parameter.name!.lexeme;
      call.add('${parameter.isNamed ? '$p: ' : ''}$p');
      parameters.add("'$p': LocalizedMessage.encodeArgument($p)");
    }
    factories.writeln(
      "LocalizedMessage $name${method.parameters!.toSource()} => LocalizedMessage(key:'$name',fallback:DomainCopy.$name(${call.join(',')}),arguments:Map<String,Object?>.unmodifiable(<String,Object?>{${parameters.join(',')}}));",
    );
  }
  out.writeln('}');
  factories.writeln('}');
  out.writeln(factories);
  out.writeln(
    'class _DomainFormatter {\n const _DomainFormatter();\n final _DomainCatalog _catalog = const _DomainCatalog();',
  );
  for (final String name in selected.toList()..sort()) {
    out.writeln(localMethods[name]!.toSource());
  }
  out.writeln(
    '}\nclass _DomainCatalog {\n const _DomainCatalog();\n final String localeName = \'en\';',
  );
  for (final String name in catalogue.toList()..sort()) {
    final MethodDeclaration? method = englishMethods[name];
    if (method == null) {
      throw StateError('English catalogue member missing: $name');
    }
    out.writeln(method.toSource().replaceAll('@override', ''));
  }
  out.writeln('}');
  final String generated = out.toString();
  final File target = File('lib/core/copy/domain_copy.g.dart');
  if (args.contains('--check')) {
    final String? problem = generatedSourceProblem(
      path: target.path.replaceAll('\\', '/'),
      actual: target.existsSync() ? target.readAsStringSync() : null,
      expected: generated,
      generator: 'tool/generate_domain_copy.dart',
    );
    if (problem != null) {
      stderr.writeln(problem);
      exitCode = 1;
    }
  } else {
    target.writeAsStringSync(generated);
    stdout.writeln(
      'Generated ${members.length} domain members from ${catalogue.length} English messages.',
    );
  }
  pureImports.sort();
  final String probe =
      '// GENERATED CODE - DO NOT MODIFY BY HAND\n// Generated by tool/generate_domain_copy.dart.\n// Imports deliberately prove compilation of each domain dependency.\n// ignore_for_file: unused_import, type=lint\n\n${pureImports.asMap().entries.map((MapEntry<int, String> e) => "import 'package:tapture/${e.value}' as domain${e.key};").join('\n')}\n\n/// Requires every migrated domain import to compile on the plain Dart VM.\nvoid verifyDomainImports() {}\n';
  final File probeFile = File('tool/domain_copy_imports.g.dart');
  if (args.contains('--check')) {
    final String? problem = generatedSourceProblem(
      path: probeFile.path.replaceAll('\\', '/'),
      actual: probeFile.existsSync() ? probeFile.readAsStringSync() : null,
      expected: probe,
      generator: 'tool/generate_domain_copy.dart',
    );
    if (problem != null) {
      stderr.writeln(problem);
      exitCode = 1;
    }
  } else {
    probeFile.writeAsStringSync(probe);
  }
}

ClassDeclaration _class(String path, {String? name}) =>
    parseString(
      content: File(path).readAsStringSync(),
    ).unit.declarations.whereType<ClassDeclaration>().firstWhere(
      (ClassDeclaration c) =>
          name == null || c.namePart.typeName.lexeme == name,
    );
