import 'dart:io';

import 'plan_source.dart';

const String _usage =
    'usage: dart run tool/sync_dev_tracker.dart [--check] [--root <repo-root>]';

/// The one generated file. The plan's prompts are never written by this tool.
const String _trackerPath = 'dev-tracker.md';

/// All outputs are prepared and validated before the first file is written.
class TrackerSnapshot {
  TrackerSnapshot(this.root, this.plan, this.outputs);

  final Directory root;
  final PlanSource plan;
  final Map<String, String> outputs;

  List<PlanStep> get steps => plan.steps;

  List<PlanTask> get tasks => plan.tasks;

  List<String> get stalePaths => <String>[
    for (final MapEntry<String, String> output in outputs.entries)
      if (!_matches(File('${root.path}/${output.key}'), output.value))
        output.key,
  ];

  /// Replaces only changed files, preserving timestamps on an unchanged run.
  List<String> write() {
    final List<String> changed = stalePaths;
    for (final String path in changed) {
      final File target = File('${root.path}/$path');
      final File temporary = File('${target.path}.sync-$pid.tmp');
      try {
        temporary.writeAsStringSync(outputs[path]!, flush: true);
        temporary.renameSync(target.path);
      } finally {
        if (temporary.existsSync()) {
          temporary.deleteSync();
        }
      }
    }
    return changed;
  }
}

Future<int> main(List<String> args) async {
  bool check = false;
  String? rootPath;
  for (int index = 0; index < args.length; index++) {
    if (args[index] == '--check' && !check) {
      check = true;
    } else if (args[index] == '--root' &&
        rootPath == null &&
        index + 1 < args.length &&
        !args[index + 1].startsWith('--')) {
      rootPath = args[++index];
    } else {
      stderr.writeln(_usage);
      return exitCode = 1;
    }
  }
  try {
    final TrackerSnapshot snapshot = readTracker(
      rootPath == null ? _defaultRoot() : Directory(rootPath),
    );
    final List<String> changed = check ? snapshot.stalePaths : snapshot.write();
    if (check && changed.isNotEmpty) {
      stderr.writeln('dev tracker: generated files are stale:');
      for (final String path in changed) {
        stderr.writeln('  $path');
      }
      stderr.writeln(
        'Run dart run tool/sync_dev_tracker.dart from frontend, then review '
        'and stage the updated tracker.',
      );
      return exitCode = 1;
    }
    stdout.writeln(
      'dev tracker: ${snapshot.steps.length} steps, '
      '${snapshot.tasks.length} tasks; '
      '${check ? 'up to date' : '${changed.length} file(s) refreshed'}',
    );
    return exitCode = 0;
  } on FormatException catch (error) {
    stderr.writeln('dev tracker: ${error.message}');
    return exitCode = 1;
  } on FileSystemException catch (error) {
    stderr.writeln('dev tracker: ${error.message}: ${error.path}');
    return exitCode = 1;
  }
}

Directory _defaultRoot() {
  Directory candidate = Directory.current.absolute;
  while (true) {
    if (Directory('${candidate.path}/dev-plan').existsSync()) {
      return candidate;
    }
    if (candidate.parent.path == candidate.path) {
      return File.fromUri(Platform.script).parent.parent.parent;
    }
    candidate = candidate.parent;
  }
}

/// Reads and validates the whole plan under [repository], then renders the
/// tracker. Throws [FormatException] naming every plan problem, before any
/// write.
TrackerSnapshot readTracker(Directory repository) {
  final Directory root = Directory(repository.resolveSymbolicLinksSync());
  final Directory planRoot = Directory('${root.path}/dev-plan');
  if (!planRoot.existsSync()) {
    throw const FormatException('missing dev-plan directory');
  }
  _rejectLink(planRoot.path);
  final PlanSource plan = readPlan(planRoot);
  if (plan.problems.isNotEmpty) {
    throw FormatException(
      plan.problems
          .map((PlanProblem p) => '${p.file}:${p.line}: ${p.message}')
          .join('\n'),
    );
  }
  _rejectLink('${root.path}/$_trackerPath');
  return TrackerSnapshot(root, plan, <String, String>{
    _trackerPath: _trackerDocument(plan),
  });
}

String _trackerDocument(PlanSource plan) {
  final List<PlanStep> steps = plan.steps;
  final List<PlanTask> tasks = plan.tasks;
  final int complete = _count(
    tasks.map((PlanTask task) => task.status),
    PlanStatus.complete,
  );
  final int percent = tasks.isEmpty ? 0 : complete * 100 ~/ tasks.length;
  final int prerequisiteReviews = tasks
      .where(
        (PlanTask task) =>
            task.status == PlanStatus.complete && task.blockers.isNotEmpty,
      )
      .length;
  final StringBuffer text = StringBuffer()
    ..writeln('# Tapture — development tracker')
    ..writeln()
    ..writeln(
      '<!-- Generated by frontend/tool/sync_dev_tracker.dart. Do not edit by hand. -->',
    )
    ..writeln()
    ..writeln(
      '**Completed tasks: $percent%** `${_progressBar(complete, tasks.length, 20)}` **$complete/${tasks.length}**',
    )
    ..writeln()
    ..writeln(
      '**Tasks:** ${_counts(tasks.map((PlanTask task) => task.status))}.',
    )
    ..writeln()
    ..writeln(
      '**Steps:** ${_counts(steps.map((PlanStep step) => step.status))}.',
    )
    ..writeln()
    ..writeln(_next(tasks))
    ..writeln();
  if (prerequisiteReviews > 0) {
    text
      ..writeln(
        '**Prerequisite review:** $prerequisiteReviews completed task(s) have unfinished prerequisites; see the [task index](#task-index).',
      )
      ..writeln();
  }
  text
    ..writeln(
      '✅ Complete · ◐ Partially complete · ○ Pending. Bars count completed tasks, not effort or release readiness.',
    )
    ..writeln()
    ..writeln('| Step | Status | Complete | Partial tasks | Pending tasks |')
    ..writeln('| --- | --- | --- | --- | --- |');
  for (final PlanStep step in steps) {
    final int done = _count(
      step.tasks.map((PlanTask task) => task.status),
      PlanStatus.complete,
    );
    final String progress = step.tasks.isEmpty
        ? '`${_progressBar(0, 0, 10)}` 0/0 (n/a)'
        : '`${_progressBar(done, step.tasks.length, 10)}` $done/${step.tasks.length}';
    text.writeln(
      '| ${step.number} · [${_escape(step.title)}](dev-plan/${step.path}) | ${_statusBadge(step.status)} | $progress | ${_taskLinks(step.tasks, PlanStatus.partial)} | ${_taskLinks(step.tasks, PlanStatus.pending)} |',
    );
  }
  text
    ..writeln()
    ..writeln(
      'Open task IDs are listed above; every task’s acceptance count and dependencies are in the [task index](#task-index).',
    )
    ..writeln()
    ..writeln(
      'Generated from task checklists; task creation, verification and pre-commit refresh it automatically. [Update rules](AGENTS.md#progress-updates).',
    )
    ..writeln()
    ..writeln('## Task index')
    ..writeln()
    ..writeln('<details>')
    ..writeln(
      '<summary>${tasks.length} tasks in implementation order, with acceptance counts and dependencies</summary>',
    )
    ..writeln()
    ..writeln(
      '| Sub-step | Task ID | Task | Status | Done | Dependencies / readiness |',
    )
    ..writeln('| --- | --- | --- | --- | ---: | --- |');
  for (final PlanTask task in tasks) {
    final String dependencies = task.dependencies.isEmpty
        ? 'None'
        : task.dependencies
              .map(
                (PlanTask dependency) =>
                    '${dependency.position} (${dependency.id})',
              )
              .join(', ');
    final List<PlanTask> blockers = task.blockers;
    final String readiness = blockers.isNotEmpty
        ? '${task.status == PlanStatus.complete ? 'Prerequisite review' : 'Waiting for'}: ${blockers.map((PlanTask task) => task.id).join(', ')}'
        : task.status == PlanStatus.complete
        ? 'Dependencies complete'
        : 'Ready';
    text.writeln(
      '| ${task.position} | ${task.id} | [${_escape(task.title)}](dev-plan/${task.href}) | **${task.status.label}** | ${task.checked}/${task.total} | $dependencies; $readiness |',
    );
  }
  text
    ..writeln()
    ..writeln('</details>');
  return text.toString();
}

String _progressBar(int complete, int total, int width) {
  final int filled = total == 0 ? 0 : complete * width ~/ total;
  return ''.padRight(filled, '█').padRight(width, '░');
}

String _statusBadge(PlanStatus status) => switch (status) {
  PlanStatus.complete => '✅ Complete',
  PlanStatus.partial => '◐ Partial',
  PlanStatus.pending => '○ Pending',
};

String _taskLinks(List<PlanTask> tasks, PlanStatus status) {
  final String links = tasks
      .where((PlanTask task) => task.status == status)
      .map((PlanTask task) => '[${task.id}](dev-plan/${task.href})')
      .join(' ');
  return links.isEmpty ? '—' : links;
}

String _next(List<PlanTask> tasks) {
  final List<PlanTask> unfinished = tasks
      .where((PlanTask task) => task.status != PlanStatus.complete)
      .toList();
  if (unfinished.isEmpty) {
    return '**Next actionable sub-step:** None — all tasks are complete.';
  }
  final List<PlanTask> ready = unfinished
      .where((PlanTask task) => task.blockers.isEmpty)
      .toList();
  if (ready.isEmpty) {
    return '**Next actionable sub-step:** None — unfinished tasks have incomplete dependencies.';
  }
  final PlanTask next = ready.first;
  return '**Next actionable sub-step:** [${next.position} · ${next.id} — ${_escape(next.title)}](dev-plan/${next.href}) (${next.status.label}; dependencies complete).';
}

String _counts(Iterable<PlanStatus> statuses) {
  final List<PlanStatus> values = statuses.toList();
  return '${values.length} total · ${_count(values, PlanStatus.complete)} Complete · ${_count(values, PlanStatus.partial)} Partially complete · ${_count(values, PlanStatus.pending)} Pending';
}

int _count(Iterable<PlanStatus> statuses, PlanStatus status) =>
    statuses.where((PlanStatus value) => value == status).length;
String _escape(String value) =>
    value.replaceAll('|', r'\|').replaceAll('[', r'\[').replaceAll(']', r'\]');
String _read(File file) => file.readAsStringSync().replaceAll('\r\n', '\n');
bool _matches(File file, String content) =>
    file.existsSync() && _read(file) == content;
void _rejectLink(String path) {
  if (FileSystemEntity.typeSync(path, followLinks: false) ==
      FileSystemEntityType.link) {
    throw FormatException(
      '$path: symbolic links are not supported in plan inputs or outputs',
    );
  }
}
