import 'package:flutter_test/flutter_test.dart';
import 'package:tapture/core/copy/copy.dart';
import 'package:tapture/core/naming/domain_names.dart';

/// Near-synonyms [frontend/test/architecture/naming_test.dart] rejects as
/// type names, plus the banned whole words the naming checker flags.
const Map<String, String> _typeSynonyms = <String, String>{
  'ProjectModel': DomainNames.project,
  'ProjectData': DomainNames.project,
  'ProjectInfo': DomainNames.project,
  'ProjectItem': DomainNames.project,
  'TemplateModel': DomainNames.templateDef,
  'TemplateData': DomainNames.templateDef,
  'TemplateInfo': DomainNames.templateDef,
  'TemplateItem': DomainNames.templateDef,
  'FieldModel': DomainNames.fieldDef,
  'FieldData': DomainNames.fieldDef,
  'FieldInfo': DomainNames.fieldDef,
  'FieldItem': DomainNames.fieldDef,
  'RecordModel': DomainNames.recordEntry,
  'RecordData': DomainNames.recordEntry,
  'RecordInfo': DomainNames.recordEntry,
  'RecordItem': DomainNames.recordEntry,
  'FieldValueModel': DomainNames.fieldValue,
  'CaptureSessionModel': DomainNames.captureSession,
  'CaptureData': DomainNames.captureSession,
  'PhotoItem': DomainNames.photoAsset,
  'PhotoModel': DomainNames.photoAsset,
  'PhotoData': DomainNames.photoAsset,
  'PhotoInfo': DomainNames.photoAsset,
  'ContextModel': DomainNames.contextState,
  'ContextData': DomainNames.contextState,
  'ContextInfo': DomainNames.contextState,
  'ReferenceData': DomainNames.referenceDataset,
  'DatasetModel': DomainNames.referenceDataset,
  'ProcessingJobModel': DomainNames.processingJob,
  'JobModel': DomainNames.processingJob,
  'BundleModel': DomainNames.bundle,
  'BundleData': DomainNames.bundle,
  'MergeModel': DomainNames.mergeSession,
  'MergeSessionModel': DomainNames.mergeSession,
};

const List<String> _bannedWords = <String>[
  'manager',
  'helper',
  'util',
  'data',
  'info',
  'item',
];

void main() {
  test('field labels carry requiredness in a placeholder message', () {
    expect(Copy.fieldLabelRequired('Name'), 'Name (required)');
    expect(Copy.fieldLabelOptional('Description'), 'Description (optional)');
  });

  test('recordsCount reads correctly at zero, one and many', () {
    expect(Copy.recordsCount(0), 'No records');
    expect(Copy.recordsCount(1), '1 record');
    expect(Copy.recordsCount(2), '2 records');
    expect(Copy.notDetected, 'Not detected');
    expect(Copy.notDetected, isNotEmpty);
  });

  test('fieldsCount reads correctly at zero, one and many', () {
    expect(Copy.fieldsCount(0), 'No fields');
    expect(Copy.fieldsCount(1), '1 field');
    expect(Copy.fieldsCount(2), '2 fields');
  });

  test('feedbackShotTipScreens names Continue later', () {
    expect(Copy.feedbackShotTipScreens, contains(Copy.feedbackContinueLater));
  });

  test('project list empty copy names create and reserves import', () {
    expect(Copy.projectsEmptyMessage, 'Create a project to start capturing.');
    expect(Copy.projectsImport, 'Import a project');
  });

  test('feedbackEntryTitle joins the number, id and message', () {
    expect(
      Copy.feedbackEntryTitle('1', 'FBK0000001', 'The list is slow'),
      '1. FBK0000001 · The list is slow',
    );
  });

  test('feedbackDownloadsGoTo names the Downloads Tapture folder', () {
    expect(Copy.downloadsTaptureFolder, 'Downloads › Tapture');
    expect(
      Copy.feedbackDownloadsGoTo(Copy.downloadsTaptureFolder),
      'Downloads go to Downloads › Tapture',
    );
    expect(Copy.feedbackOpenFolder, 'Open folder');
    expect(Copy.feedbackSaveToFolder, 'Save to a folder');
    expect(
      Copy.feedbackOpenFolderFailed(Copy.downloadsTaptureFolder),
      'The folder could not be opened. Look in Downloads › Tapture.',
    );
  });

  test('feedbackDiscardDraftMessage reads correctly at zero, one and many', () {
    expect(Copy.feedbackDiscardDraftTitle, 'Discard this feedback?');
    expect(
      Copy.feedbackDiscardDraftMessage(0),
      'This feedback will be cleared.',
    );
    expect(
      Copy.feedbackDiscardDraftMessage(1),
      'This feedback and its 1 image will be cleared.',
    );
    expect(
      Copy.feedbackDiscardDraftMessage(3),
      'This feedback and its 3 images will be cleared.',
    );
  });

  test('no Copy value uses a synonym the naming checker rejects', () {
    for (final String value in _values) {
      expect(value, isNotEmpty);
      for (final MapEntry<String, String> synonym in _typeSynonyms.entries) {
        expect(
          value.contains(synonym.key),
          isFalse,
          reason:
              '"$value" uses ${synonym.key}; say ${synonym.value} '
              '(FE-CONS-07)',
        );
      }
      for (final String banned in _bannedWords) {
        expect(
          RegExp('\\b$banned\\b', caseSensitive: false).hasMatch(value),
          isFalse,
          reason: '"$value" uses "$banned", which the naming checker rejects',
        );
      }
    }
  });
}

/// Every catalogue string [Copy] currently publishes.
List<String> get _values {
  return <String>[
    Copy.notDetected,
    Copy.recordsCount(0),
    Copy.recordsCount(1),
    Copy.recordsCount(2),
    Copy.fieldsCount(0),
    Copy.fieldsCount(1),
    Copy.fieldsCount(2),
    Copy.clearField('Name'),
    Copy.showField('PIN'),
    Copy.hideField('PIN'),
    Copy.autoFilled,
    Copy.outOfRange,
    Copy.selectAll,
    Copy.clear,
    Copy.dismissChip('Water'),
    Copy.dismiss,
    Copy.cancel,
    Copy.ok,
    Copy.discardChangesTitle,
    Copy.unsavedChanges,
    Copy.discard,
    Copy.fixFields(1),
    Copy.fixFields(2),
    Copy.fieldError('Name', 'Required'),
    Copy.fieldLabelRequired('Name'),
    Copy.fieldLabelOptional('Description'),
    Copy.validationAnnouncement('Fix these fields', <String>['Name: Required']),
    Copy.missingPhoto,
    Copy.missingPhotoNamed('Front'),
    Copy.photo,
    Copy.photoThumbLabel(
      type: Copy.photoFront,
      missing: false,
      captioned: true,
      selected: true,
    ),
    Copy.photoFront,
    Copy.photoBack,
    Copy.photoSerial,
    Copy.photoRatingPlate,
    Copy.photoRatingPlateBadge,
    Copy.photoDamage,
    Copy.photoPanel,
    Copy.photoLocation,
    Copy.photoAttendance,
    Copy.photoAttendanceBadge,
    Copy.photoDocument,
    Copy.photoDocumentBadge,
    Copy.photoOther,
    Copy.stepDone,
    Copy.stepRunning,
    Copy.stepWaiting,
    Copy.failed,
    Copy.progressAnnouncement(label: 'Read text', state: Copy.stepWaiting),
    Copy.statusDraft,
    Copy.statusCaptured,
    Copy.statusQueued,
    Copy.statusProcessing,
    Copy.statusExtracted,
    Copy.statusNeedsReview,
    Copy.statusApproved,
    Copy.statusArchived,
    Copy.statusDeleted,
    Copy.emptyHeadline,
    Copy.emptyMessage,
    Copy.loading,
    Copy.busy,
    Copy.busyAction('Save'),
    Copy.tryAgain,
    Copy.save,
    Copy.undo,
    Copy.galleryTitle,
    Copy.galleryTheme,
    Copy.galleryWidth,
    Copy.galleryTextScale,
    Copy.galleryTokens,
    Copy.galleryLayout,
    Copy.galleryButtons,
    Copy.galleryFields,
    Copy.galleryContainers,
    Copy.galleryStates,
    Copy.galleryFeedback,
    Copy.galleryLight,
    Copy.galleryDark,
    Copy.galleryOutdoor,
    Copy.galleryCompact,
    Copy.galleryMedium,
    Copy.galleryExpanded,
    Copy.galleryScale100,
    Copy.galleryScale200,
    Copy.appName,
    Copy.search,
    Copy.overflowMenu,
    Copy.navProjects,
    Copy.projectsEmptyHeadline,
    Copy.projectsEmptyMessage,
    Copy.projectsCreate,
    Copy.projectsImport,
    Copy.projectsDuplicate,
    Copy.projectAllProjects,
    Copy.projectNew,
    Copy.projectArchive,
    Copy.projectUnarchive,
    Copy.projectDelete,
    Copy.projectDeleteTitle('Alpha'),
    Copy.projectDeleteMessage(records: 2, files: 1, days: 30),
    Copy.filesCount(0),
    Copy.filesCount(1),
    Copy.filesCount(2),
    Copy.projectDeleteTypeName,
    Copy.projectExportFirst,
    Copy.projectShowArchived,
    Copy.projectCreateTitle,
    Copy.projectDuplicateTitle,
    Copy.projectName,
    Copy.projectDescription,
    Copy.projectOrganisation,
    Copy.projectEditTitle,
    Copy.projectSettingsTitle,
    Copy.projectStartsOn,
    Copy.projectEndsOn,
    Copy.projectStatus,
    Copy.projectStatusActive,
    Copy.projectStatusArchived,
    Copy.projectAiEnabled,
    Copy.projectAiEnabledEffect,
    Copy.projectDoNotSendImages,
    Copy.projectDoNotSendImagesEffect,
    Copy.projectRefineColumns,
    Copy.projectConfidenceHigh,
    Copy.projectConfidenceMedium,
    Copy.projectUseAppDefault,
    Copy.projectOn,
    Copy.projectOff,
    Copy.projectAppDefault(Copy.projectOn),
    Copy.projectEditEmptyHeadline,
    Copy.projectEditEmptyMessage,
    Copy.projectSettingsEmptyHeadline,
    Copy.projectSettingsEmptyMessage,
    Copy.projectCopyName('Alpha'),
    Copy.projectLastWorked(DateTime.utc(2026, 9, 17)),
    Copy.projectListSubtitle(
      records: 2,
      unprocessed: 1,
      lastWorked: Copy.projectLastWorked(DateTime.utc(2026, 9, 17)),
    ),
    Copy.continueCapturing,
    Copy.homeReview,
    Copy.homeProcess,
    Copy.homeExport,
    Copy.homeShare,
    Copy.homeEmptyHeadline,
    Copy.homeEmptyMessage,
    Copy.homeReviewPending(0),
    Copy.homeReviewPending(1),
    Copy.homeReviewPending(2),
    Copy.homeProcessPending(0),
    Copy.homeProcessPending(1),
    Copy.homeProcessPending(2),
    Copy.homeExportPending(0),
    Copy.homeExportPending(1),
    Copy.homeExportPending(2),
    Copy.homeSharePending(0),
    Copy.homeSharePending(1),
    Copy.homeSharePending(2),
    Copy.navCapture,
    Copy.navRecords,
    Copy.navMore,
    Copy.navTemplates,
    Copy.templatesEmptyHeadline,
    Copy.templatesEmptyMessage,
    Copy.templatesPickLibrary,
    Copy.templatesCreate,
    Copy.templatesCreateTitle,
    Copy.templatesOpen,
    Copy.templatesExport,
    Copy.templatesImport,
    Copy.templatesImportEmptyHeadline,
    Copy.templatesImportEmptyMessage,
    Copy.templatesImportUnknownSchema,
    Copy.templatesImportUnknownSchemaRecovery,
    Copy.templatesImportInvalid,
    Copy.templatesImportInvalidRecovery,
    Copy.templatesImportDuplicateField,
    Copy.templatesImportDuplicateFieldRecovery,
    Copy.workbookPassword,
    Copy.workbookPasswordRecovery,
    Copy.workbookCorrupt,
    Copy.workbookCorruptRecovery,
    Copy.xlsxMappingTitle,
    Copy.xlsxMappingEmptyHeadline,
    Copy.xlsxMappingEmptyMessage,
    Copy.xlsxMappingConfirm,
    Copy.xlsxMappingSkip,
    Copy.xlsxMappingInclude,
    Copy.xlsxMappingSkipped,
    Copy.xlsxMappingProposal(
      field: 'Serial',
      type: Copy.fieldTypeLabel('text'),
      rule: Copy.fieldOptional,
    ),
    Copy.xlsxMappingUntitled('A'),
    Copy.xlsxMappingDefaultName,
    Copy.xlsxMappingMissing,
    Copy.xlsxMappingMissingRecovery,
    Copy.xlsxMappingExists,
    Copy.xlsxMappingExistsRecovery,
    Copy.templatesDelete,
    Copy.templatesDeleteTitle('Assets'),
    Copy.templatesDeleteMessage(fields: 2, records: 0),
    Copy.templateFieldsTitle,
    Copy.templatesAddField,
    Copy.templatesEditField,
    Copy.templatesDeleteField,
    Copy.templatesDeleteFieldTitle('Serial'),
    Copy.templatesDeleteFieldMessage(values: 0),
    Copy.templatesDeleteFieldMessage(values: 1),
    Copy.templatesDeleteFieldMessage(values: 2),
    Copy.templatesFieldsEmptyHeadline,
    Copy.templatesFieldsEmptyMessage,
    Copy.fieldRequired,
    Copy.fieldRecommended,
    Copy.fieldOptional,
    Copy.fieldMoveUp('Serial'),
    Copy.fieldMoveDown('Serial'),
    Copy.fieldReorder('Serial'),
    Copy.fieldTypeLabel('text'),
    Copy.fieldTypeLabel('longText'),
    Copy.fieldTypeLabel('number'),
    Copy.fieldTypeLabel('decimal'),
    Copy.fieldTypeLabel('currency'),
    Copy.fieldTypeLabel('percentage'),
    Copy.fieldTypeLabel('date'),
    Copy.fieldTypeLabel('time'),
    Copy.fieldTypeLabel('dateTime'),
    Copy.fieldTypeLabel('boolean'),
    Copy.fieldTypeLabel('choice'),
    Copy.fieldTypeLabel('multiChoice'),
    Copy.fieldTypeLabel('lookup'),
    Copy.fieldTypeLabel('barcode'),
    Copy.fieldTypeLabel('photoReference'),
    Copy.fieldTypeLabel('documentReference'),
    Copy.fieldTypeLabel('gpsLocation'),
    Copy.fieldTypeLabel('signature'),
    Copy.fieldTypeLabel('computed'),
    Copy.fieldLabel,
    Copy.fieldType,
    Copy.fieldRequiredness,
    Copy.fieldAdvanced,
    Copy.fieldAdvancedShow,
    Copy.fieldAdvancedHide,
    Copy.fieldKeepAnyway,
    Copy.fieldTwoFactsWarning,
    Copy.fieldDefaultValue,
    Copy.fieldUnit,
    Copy.fieldHelp,
    Copy.fieldInputMode,
    Copy.fieldInputAny,
    Copy.fieldInputManual,
    Copy.fieldInputAi,
    Copy.fieldInputAuto,
    Copy.fieldStickable,
    Copy.fieldContextLevel,
    Copy.fieldAutoFill,
    Copy.fieldAutoFillNone,
    Copy.fieldAutoFillLabel('now'),
    Copy.fieldAutoFillLabel('today'),
    Copy.fieldAutoFillLabel('time'),
    Copy.fieldAutoFillLabel('sequence'),
    Copy.fieldAutoFillLabel('operator'),
    Copy.fieldAutoFillLabel('device'),
    Copy.fieldAutoFillLabel('gps'),
    Copy.fieldAutoFillLabel('context'),
    Copy.fieldRefine,
    Copy.fieldIdentity,
    Copy.fieldRequiredWhen,
    Copy.fieldRequiredWhenPreview('Fault present is yes'),
    Copy.fieldHidden,
    Copy.fieldHiddenHelp,
    Copy.fieldValidationTitle,
    Copy.fieldValidationEmptyHeadline,
    Copy.fieldValidationEmptyMessage,
    Copy.fieldPattern,
    Copy.fieldPatternNone,
    Copy.fieldPatternSerial,
    Copy.fieldPatternAssetTag,
    Copy.fieldPatternRegistration,
    Copy.fieldPatternCustom,
    Copy.fieldPatternTest,
    Copy.fieldPatternTestPass,
    Copy.fieldMinLength,
    Copy.fieldMaxLength,
    Copy.fieldRangeMin,
    Copy.fieldRangeMax,
    Copy.fieldRequiredWith,
    Copy.fieldOptionsTitle,
    Copy.fieldOptionsEmptyHeadline,
    Copy.fieldOptionsEmptyMessage,
    Copy.fieldOptionLabel,
    Copy.fieldOptionAdd,
    Copy.fieldOptionRetire,
    Copy.fieldOptionRetired,
    Copy.fieldAddEmptyHeadline,
    Copy.fieldAddEmptyMessage,
    Copy.requiredColumnsTitle,
    Copy.requiredColumnsEmptyHeadline,
    Copy.requiredColumnsEmptyMessage,
    Copy.requiredColumnHide,
    Copy.requiredColumnShowGroup,
    Copy.requiredColumnHideGroup,
    Copy.requiredColumnUngrouped,
    Copy.requiredColumnRadios('Serial'),
    Copy.requiredColumnCell('Serial', Copy.fieldRequired),
    Copy.requiredColumnShipped(Copy.fieldOptional),
    Copy.requiredColumnGroup('identity'),
    Copy.identityFieldsTitle,
    Copy.identityFieldsExplain,
    Copy.identityFieldsEmptyHeadline,
    Copy.identityFieldsEmptyMessage,
    Copy.outputMappingTitle,
    Copy.outputMappingEmptyHeadline,
    Copy.outputMappingEmptyMessage,
    Copy.outputMappingDuplicate,
    Copy.outputMappingDuplicateRecovery,
    Copy.outputMappingBuiltHint,
    Copy.outputMappingImportedHint,
    Copy.templateMigrationTitle,
    Copy.templateMigrationExplain,
    Copy.templateMigrationEmptyHeadline,
    Copy.templateMigrationEmptyMessage,
    Copy.templateMigrationAdded,
    Copy.templateMigrationRemoved,
    Copy.templateMigrationRetyped,
    Copy.templateMigrationConfirmTitle,
    Copy.templateMigrationConfirm,
    Copy.templateMigrationAction,
    Copy.templateCopyName('Assets'),
    Copy.templateListSubtitle(fields: 2, records: 0),
    Copy.templatesLibraryTitle,
    Copy.templatesLibraryEmptyHeadline,
    Copy.templatesLibraryEmptyMessage,
    Copy.templatesAdd,
    Copy.shippedTemplateName('equipment_asset'),
    Copy.shippedTemplateName('medical_equipment'),
    Copy.shippedTemplateName('ict_equipment'),
    Copy.shippedTemplateName('vehicle_plant'),
    Copy.shippedTemplateName('furniture_fitting'),
    Copy.shippedTemplateName('building_facility'),
    Copy.shippedTemplateName('room_space'),
    Copy.shippedTemplateName('utility_point'),
    Copy.shippedTemplateName('stock_item'),
    Copy.shippedTemplateName('inspection_check'),
    Copy.shippedTemplateName('work_order'),
    Copy.shippedTemplateName('meter_reading'),
    Copy.shippedTemplateName('person_beneficiary'),
    Copy.shippedTemplateName('staff_member'),
    Copy.shippedTemplateName('household_survey'),
    Copy.shippedTemplateName('land_parcel'),
    Copy.shippedTemplateName('plant_tree'),
    Copy.shippedTemplateName('livestock_animal'),
    Copy.shippedTemplateName('document_record'),
    Copy.shippedTemplateName('meeting'),
    Copy.shippedTemplateName('event_activity'),
    Copy.shippedTemplateName('incident_report'),
    Copy.shippedTemplateName('generic_item'),
    Copy.shippedKindTitle('equipment'),
    Copy.shippedKindTitle('medical'),
    Copy.shippedKindTitle('ict'),
    Copy.shippedKindTitle('vehicle'),
    Copy.shippedKindTitle('furniture'),
    Copy.shippedKindTitle('building'),
    Copy.shippedKindTitle('room'),
    Copy.shippedKindTitle('utility'),
    Copy.shippedKindTitle('stock'),
    Copy.shippedKindTitle('inspection'),
    Copy.shippedKindTitle('work_order'),
    Copy.shippedKindTitle('meter'),
    Copy.shippedKindTitle('person'),
    Copy.shippedKindTitle('staff'),
    Copy.shippedKindTitle('household'),
    Copy.shippedKindTitle('land'),
    Copy.shippedKindTitle('plant'),
    Copy.shippedKindTitle('livestock'),
    Copy.shippedKindTitle('document'),
    Copy.shippedKindTitle('meeting'),
    Copy.shippedKindTitle('event'),
    Copy.shippedKindTitle('incident'),
    Copy.shippedKindTitle('generic'),
    Copy.shippedLabel('templates.equipment_asset.asset_tag'),
    Copy.navQueue,
    Copy.navExports,
    Copy.operatorNameUse,
    Copy.operatorName,
    Copy.operatorProfileTitle,
    Copy.operatorInitials,
    Copy.operatorContact,
    Copy.operatorEmail,
    Copy.operatorPhone,
    Copy.nameRequired,
    Copy.emailNeedsAt,
    Copy.initialsLength,
    Copy.statusNoProject,
    Copy.statusNoContext,
    Copy.statusNoTemplate,
    Copy.statusWhere('Alpha', 'Ward 1'),
    Copy.networkOnline,
    Copy.networkMetered,
    Copy.networkOffline,
    Copy.networkOfflineByChoice,
    Copy.settingsOfflineTitle,
    Copy.settingsOfflineEffect,
    Copy.unprocessedCount(0),
    Copy.unprocessedCount(1),
    Copy.unprocessedCount(2),
    Copy.offlineWorking,
    Copy.somethingWentWrong,
    Copy.workStillOnDevice,
    Copy.restart,
    Copy.exportLog,
    Copy.openRecycleBin,
    Copy.settingsTitle,
    Copy.settingsOperatorSubtitle,
    Copy.settingsCaptureSubtitle,
    Copy.settingsAiTitle,
    Copy.settingsAiSubtitle,
    Copy.settingsLanguageTitle,
    Copy.settingsLanguageSubtitle,
    Copy.settingsAppearanceTitle,
    Copy.settingsAppearanceSubtitle,
    Copy.themeModeSystem,
    Copy.themeModeLight,
    Copy.themeModeDark,
    Copy.themeModeOutdoor,
    Copy.settingsStorageTitle,
    Copy.settingsStorageSubtitle,
    Copy.settingsFilesTitle,
    Copy.settingsFilesSubtitle,
    Copy.settingsSecurityTitle,
    Copy.settingsSecuritySubtitle,
    Copy.settingsAboutTitle,
    Copy.settingsAboutSubtitle,
    Copy.settingsCamera,
    Copy.settingsCameraEffect,
    Copy.settingsCameraPhoto,
    Copy.settingsAutoFillDates,
    Copy.settingsAutoFillDatesEffect,
    Copy.settingsGps,
    Copy.settingsGpsWhyOff,
    Copy.settingsPhotoQuality,
    Copy.settingsPhotoQualityEffect,
    Copy.settingsQualityStandard,
    Copy.settingsQualitySmaller,
    Copy.settingsFolderStrategy,
    Copy.settingsFolderStrategyNewFilesOnly,
    Copy.settingsFolderByContext,
    Copy.settingsFolderByTemplate,
    Copy.settingsFolderByDate,
    Copy.settingsFolderFlat,
    Copy.settingsNamingPattern,
    Copy.settingsNamingPatternEffect,
    Copy.settingsCameraSubtitle('Photo'),
    Copy.settingsPhotoQualitySubtitle('Standard'),
    Copy.settingsNamingSubtitle('{date}_{time}_{type}'),
    Copy.settingsFolderStrategySubtitle('By context'),
    Copy.settingsProjectsHeader,
    Copy.settingsHeadroomHeader,
    Copy.settingsRetentionHeader,
    Copy.settingsHeadroomAmple,
    Copy.settingsHeadroomLow,
    Copy.settingsHeadroomCritical,
    Copy.settingsClearCache,
    Copy.settingsClearCacheEffect,
    Copy.settingsCacheSize('12 B'),
    Copy.settingsRetentionSubtitle(30),
    Copy.settingsClearCacheTitle,
    Copy.settingsClearCacheMessage,
    Copy.settingsRetention,
    Copy.settingsRetentionEffect,
    Copy.settingsRetentionDays(0),
    Copy.settingsRetentionDays(1),
    Copy.settingsRetentionDays(2),
    Copy.settingsDocuments,
    Copy.settingsAudio,
    Copy.settingsExports,
    Copy.settingsCache,
    Copy.settingsStorageEmptyHeadline,
    Copy.settingsStorageEmptyMessage,
    Copy.fileSize(12),
    Copy.fileSize(2048),
    Copy.fileSize(2 * 1024 * 1024),
    Copy.settingsProjectUse(
      photos: '1 B',
      documents: '0 B',
      audio: '0 B',
      exports: '0 B',
    ),
    Copy.settingsVersion,
    Copy.settingsBuild,
    Copy.settingsLicences,
    Copy.settingsLicencesEffect,
    Copy.settingsPlan,
    Copy.settingsSpecification,
    Copy.settingsPlanUrl,
    Copy.settingsSpecificationUrl,
    Copy.settingsEmptyHeadline,
    Copy.settingsEmptyMessage,
    Copy.settingsCaptureEmptyHeadline,
    Copy.settingsCaptureEmptyMessage,
    Copy.settingsAboutEmptyHeadline,
    Copy.settingsAboutEmptyMessage,
    Copy.appLockUnlockTitle,
    Copy.appLockTitle,
    Copy.appLockPin,
    Copy.appLockCurrentPin,
    Copy.appLockNewPin,
    Copy.appLockConfirmPin,
    Copy.appLockSet,
    Copy.appLockChange,
    Copy.appLockRemove,
    Copy.appLockUnlock,
    Copy.appLockBiometrics,
    Copy.appLockSetEffect,
    Copy.appLockRemoveEffect,
    Copy.appLockOn,
    Copy.appLockOff,
    Copy.appLockPinLength,
    Copy.appLockPinMismatch,
    Copy.appLockWrongPin,
    Copy.appLockRecovery,
    Copy.appLockWait(Duration.zero),
    Copy.appLockWait(const Duration(seconds: 2)),
    Copy.close,
    Copy.feedback,
    Copy.feedbackButtonHint,
    Copy.feedbackGive,
    Copy.feedbackDownload,
    Copy.feedbackDelete,
    Copy.feedbackStaysOnDevice,
    Copy.feedbackCategoryGeneral,
    Copy.feedbackCategoryImprovement,
    Copy.feedbackCategoryError,
    Copy.feedbackCategorySuggestion,
    Copy.feedbackCategoryOther,
    Copy.feedbackSubmitterSignedIn,
    Copy.feedbackSubmitterLocal,
    Copy.feedbackSubmitterAnonymous,
    Copy.feedbackDeviceMobile,
    Copy.feedbackDeviceTablet,
    Copy.feedbackDeviceDesktop,
    Copy.feedbackType,
    Copy.feedbackOtherType,
    Copy.feedbackOtherRequired,
    Copy.feedbackMessage,
    Copy.feedbackMessageHint,
    Copy.feedbackMessageRequired,
    Copy.feedbackAttachScreenshot,
    Copy.feedbackContinue,
    Copy.feedbackAddScreen,
    Copy.feedbackIncludeUi,
    Copy.feedbackAddWindow,
    Copy.feedbackStopSharing,
    Copy.feedbackSharingWindow,
    Copy.feedbackOtherWindow,
    Copy.feedbackTakePhoto,
    Copy.feedbackChoosePhoto,
    Copy.feedbackShotTipScreens,
    Copy.feedbackShotTipApps,
    Copy.feedbackRemoveShot('Projects'),
    Copy.feedbackShotPreview,
    Copy.feedbackDiscardDraft,
    Copy.feedbackDiscardDraftTitle,
    Copy.feedbackDiscardDraftMessage(0),
    Copy.feedbackDiscardDraftMessage(1),
    Copy.feedbackDiscardDraftMessage(3),
    Copy.feedbackContinueLater,
    Copy.feedbackDraftBarHint,
    Copy.feedbackShotAdded('Projects'),
    Copy.feedbackAttachImages(1),
    Copy.feedbackAttachImages(3),
    Copy.feedbackImageCount(1),
    Copy.feedbackImageCount(2),
    Copy.feedbackShotsFull,
    Copy.feedbackScreenshotOf('Projects'),
    Copy.feedbackNoScreenshot,
    Copy.feedbackScreenshotPreview,
    Copy.feedbackSave,
    Copy.feedbackSaved,
    Copy.feedbackTypes,
    Copy.feedbackFrom,
    Copy.feedbackTo,
    Copy.feedbackRangeBackwards,
    Copy.feedbackScreens,
    Copy.feedbackPlatforms,
    Copy.feedbackDeviceTypes,
    Copy.feedbackSubmittedBy,
    Copy.feedbackScreenshot,
    Copy.feedbackScreenshotAny,
    Copy.feedbackScreenshotWith,
    Copy.feedbackScreenshotWithout,
    Copy.feedbackSearch,
    Copy.feedbackClearFilters,
    Copy.feedbackMoreFilters(0),
    Copy.feedbackMoreFilters(1),
    Copy.feedbackMoreFilters(3),
    Copy.feedbackFewerFilters,
    Copy.dictateInto('Your feedback'),
    Copy.stopDictating('Your feedback'),
    Copy.photoNoAccess,
    Copy.displayNoAccess,
    Copy.photoNoCamera,
    Copy.photoPickFailed,
    Copy.displayCaptureFailed,
    Copy.dictationUnavailable,
    Copy.dictationNoMicrophone,
    Copy.dictationNothingHeard,
    Copy.dictationNeedsConnection,
    Copy.dictationOfflineOnly,
    Copy.dictationFailed,
    Copy.feedbackMatching(0, 1),
    Copy.feedbackMatching(1, 1),
    Copy.feedbackMatching(2, 2),
    Copy.feedbackDownloadCount(0),
    Copy.feedbackDownloadCount(1),
    Copy.feedbackDownloadCount(2),
    Copy.feedbackDownloadStarted,
    Copy.feedbackDownloadedTo('downloads/file.xlsx'),
    Copy.downloadsTaptureFolder,
    Copy.feedbackDownloadsGoTo(Copy.downloadsTaptureFolder),
    Copy.feedbackOpenFolder,
    Copy.feedbackSaveToFolder,
    Copy.feedbackOpenFolderFailed(Copy.downloadsTaptureFolder),
    Copy.feedbackEmptyHeadline,
    Copy.feedbackEmptyMessage,
    Copy.feedbackNoMatchHeadline,
    Copy.feedbackNoMatchMessage,
    Copy.feedbackSelected(0),
    Copy.feedbackSelected(1),
    Copy.feedbackSelected(2),
    Copy.feedbackDeleteCount(0),
    Copy.feedbackDeleteCount(1),
    Copy.feedbackDeleteCount(2),
    Copy.feedbackDeleteTitle(1),
    Copy.feedbackDeleteTitle(2),
    Copy.feedbackDeleteMessage(1),
    Copy.feedbackDeleteMessage(2),
    Copy.feedbackDeleted(1),
    Copy.feedbackDeleted(2),
    Copy.feedbackShowMore,
    Copy.feedbackEntryFacts('Improvement', '18 Sep 2026, 10:02', 'Projects'),
    Copy.feedbackEntryTitle('1', 'FBK0000001', 'The list is slow'),
  ];
}
