// Generated by frontend/tool/whisper_vendor.dart from src/whisper_sources.cmake
// (dev-plan task 102). Do not edit; re-run the tool instead.
#include "../../../../../third_party/whisper.cpp/ggml/src/ggml-cpu/ops.h"
