// Generated by tool/branding/generate.mjs. Do not edit.

/// Typed paths for runtime artwork and the complete generated resource inventory.
abstract final class BrandingAssets {
  /// The mark resource.
  static const String mark = 'assets/branding/tapture-mark.svg';

  /// The markInverse resource.
  static const String markInverse = 'assets/branding/tapture-mark-inverse.svg';

  /// The markPng resource.
  static const String markPng = 'assets/branding/tapture-mark-512.png';

  /// The markInversePng resource.
  static const String markInversePng =
      'assets/branding/tapture-mark-inverse-512.png';

  /// The lockup resource.
  static const String lockup = 'assets/branding/tapture-lockup-horizontal.svg';

  /// The lockupInverse resource.
  static const String lockupInverse =
      'assets/branding/tapture-lockup-horizontal-inverse.svg';

  /// The lockupStacked resource.
  static const String lockupStacked =
      'assets/branding/tapture-lockup-stacked.svg';

  /// The lockupPng resource.
  static const String lockupPng =
      'assets/branding/tapture-lockup-horizontal-2048.png';

  /// The splashLight resource.
  static const String splashLight = 'assets/branding/splash-light.svg';

  /// The splashDark resource.
  static const String splashDark = 'assets/branding/splash-dark.svg';

  /// The splashOutdoor resource.
  static const String splashOutdoor = 'assets/branding/splash-outdoor.svg';

  /// The favicon resource.
  static const String favicon = 'assets/branding/favicon.svg';

  /// The manifest resource.
  static const String manifest = 'assets/branding/manifest.json';

  /// Every generated path; platform resources are bundled by their toolchains.
  static const List<String> generated = <String>[
    'android/app/src/main/res/drawable-hdpi/ic_launcher_background.png',
    'android/app/src/main/res/drawable-hdpi/ic_launcher_foreground.png',
    'android/app/src/main/res/drawable-hdpi/ic_launcher_monochrome.png',
    'android/app/src/main/res/drawable-hdpi/splash_mark.png',
    'android/app/src/main/res/drawable-mdpi/ic_launcher_background.png',
    'android/app/src/main/res/drawable-mdpi/ic_launcher_foreground.png',
    'android/app/src/main/res/drawable-mdpi/ic_launcher_monochrome.png',
    'android/app/src/main/res/drawable-mdpi/splash_mark.png',
    'android/app/src/main/res/drawable-night-hdpi/splash_mark.png',
    'android/app/src/main/res/drawable-night-mdpi/splash_mark.png',
    'android/app/src/main/res/drawable-night-xhdpi/splash_mark.png',
    'android/app/src/main/res/drawable-night-xxhdpi/splash_mark.png',
    'android/app/src/main/res/drawable-night-xxxhdpi/splash_mark.png',
    'android/app/src/main/res/drawable-v21/launch_background.xml',
    'android/app/src/main/res/drawable-xhdpi/ic_launcher_background.png',
    'android/app/src/main/res/drawable-xhdpi/ic_launcher_foreground.png',
    'android/app/src/main/res/drawable-xhdpi/ic_launcher_monochrome.png',
    'android/app/src/main/res/drawable-xhdpi/splash_mark.png',
    'android/app/src/main/res/drawable-xxhdpi/ic_launcher_background.png',
    'android/app/src/main/res/drawable-xxhdpi/ic_launcher_foreground.png',
    'android/app/src/main/res/drawable-xxhdpi/ic_launcher_monochrome.png',
    'android/app/src/main/res/drawable-xxhdpi/splash_mark.png',
    'android/app/src/main/res/drawable-xxxhdpi/ic_launcher_background.png',
    'android/app/src/main/res/drawable-xxxhdpi/ic_launcher_foreground.png',
    'android/app/src/main/res/drawable-xxxhdpi/ic_launcher_monochrome.png',
    'android/app/src/main/res/drawable-xxxhdpi/splash_mark.png',
    'android/app/src/main/res/drawable/launch_background.xml',
    'android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml',
    'android/app/src/main/res/mipmap-hdpi/ic_launcher.png',
    'android/app/src/main/res/mipmap-mdpi/ic_launcher.png',
    'android/app/src/main/res/mipmap-xhdpi/ic_launcher.png',
    'android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png',
    'android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png',
    'android/app/src/main/res/values-night-v31/styles.xml',
    'android/app/src/main/res/values-night/colors.xml',
    'android/app/src/main/res/values-night/styles.xml',
    'android/app/src/main/res/values-v31/styles.xml',
    'android/app/src/main/res/values/colors.xml',
    'android/app/src/main/res/values/styles.xml',
    'assets/branding/favicon.svg',
    'assets/branding/manifest.json',
    'assets/branding/splash-dark.svg',
    'assets/branding/splash-light.svg',
    'assets/branding/splash-outdoor.svg',
    'assets/branding/tapture-lockup-horizontal-2048.png',
    'assets/branding/tapture-lockup-horizontal-inverse.svg',
    'assets/branding/tapture-lockup-horizontal.svg',
    'assets/branding/tapture-lockup-stacked.svg',
    'assets/branding/tapture-mark-512.png',
    'assets/branding/tapture-mark-inverse-512.png',
    'assets/branding/tapture-mark-inverse.svg',
    'assets/branding/tapture-mark.svg',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png',
    'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png',
    'ios/Runner/Assets.xcassets/LaunchBackground.colorset/Contents.json',
    'ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json',
    'ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage-dark.png',
    'ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage-dark@2x.png',
    'ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage-dark@3x.png',
    'ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png',
    'ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png',
    'ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png',
    'ios/Runner/Base.lproj/LaunchScreen.storyboard',
    'lib/core/assets/branding_assets.dart',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_128.png',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_16.png',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_256.png',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_32.png',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png',
    'macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_64.png',
    'web/favicon.png',
    'web/favicon.svg',
    'web/icons/Icon-192.png',
    'web/icons/Icon-512.png',
    'web/icons/Icon-maskable-192.png',
    'web/icons/Icon-maskable-512.png',
    'web/icons/apple-touch-icon.png',
    'web/manifest.json',
    'windows/runner/resources/app_icon.ico',
  ];
}
