// Generated by frontend/tool/whisper_vendor.dart from src/whisper_sources.cmake
// (dev-plan task 102). Do not edit; re-run the tool instead.
#if defined(__aarch64__)
#include "../../../../third_party/whisper.cpp/ggml/src/ggml-cpu/arch/arm/quants.c"
#elif defined(__x86_64__)
#include "../../../../third_party/whisper.cpp/ggml/src/ggml-cpu/arch/x86/quants.c"
#endif
