/// The quality feature: validation, duplicates, conflicts and variance.
library;

export 'data/quality_repository_impl.dart'
    show QualityRepositoryImpl, qualityRepositoryProvider;
export 'data/variance_writer.dart' show VarianceWriter;
export 'domain/conflict_detection.dart';
export 'domain/consent_field.dart' show ConsentField;
export 'domain/duplicate_candidate.dart';
export 'domain/duplicate_choice.dart';
export 'domain/duplicate_detection.dart';
export 'domain/duplicate_ledger.dart';
export 'domain/duplicate_link.dart';
export 'domain/duplicate_override.dart';
export 'domain/duplicate_pair_view.dart';
export 'domain/duplicate_resolution.dart';
export 'domain/duplicate_side.dart';
export 'domain/duplicate_signal.dart';
export 'domain/duplicate_signals.dart';
export 'domain/duplicate_subject.dart';
export 'domain/field_conflict.dart';
export 'domain/field_variance.dart';
export 'domain/identity_hash.dart';
export 'domain/possible_duplicate.dart';
export 'domain/quality_counts.dart';
export 'domain/quality_repository.dart';
export 'domain/record_rules.dart';
export 'domain/record_variance.dart';
export 'domain/uncaptured_rows.dart';
export 'domain/value_candidate.dart';
export 'domain/variance_computation.dart';
export 'domain/verification_prefill.dart';
export 'presentation/conflict_resolution_row.dart';
export 'presentation/duplicate_choice_controller.dart';
export 'presentation/duplicate_compare_screen.dart';
export 'presentation/duplicate_flow.dart';
export 'presentation/duplicate_links.dart';
export 'presentation/duplicate_merge_controller.dart';
export 'presentation/duplicate_merge_sheet.dart';
export 'presentation/duplicate_prompt.dart';
export 'presentation/duplicates_controller.dart';
export 'presentation/duplicates_screen.dart';
export 'presentation/quality_providers.dart';
export 'presentation/quality_summary_screen.dart';
export 'presentation/variance_filter_controller.dart';
export 'presentation/variance_screen.dart';
export 'presentation/verification_mode_toggle.dart';
export 'presentation/verification_session.dart';
